MvcMusicStore333/Controllers/UserDefined/ShoppingCartController.cs
using MvcMusicStore333.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMusicStore333.Controllers
{
    public class ShoppingCartController : Controller
    {
        Context context = new Context();

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedAlbum = context.Albums.Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = context.Carts.Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) + " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

MvcMusicStore333/Controllers/UserDefined/StoreController.cs
using MvcMusicStore333.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcMusicStore3.Controllers
{
    public class StoreController : Controller
    {
        Context context = new Context();
        // GET: Store
        public ActionResult Index()
        {
            var genres = context.Genres.ToList();
            return View(genres);
        }
        public ActionResult Browse(int genreId)
        {
            var genre = context.Genres.Include("Albums").Single(g => g.GenreId == genreId);
            return View(genre);
        }
        public ActionResult Details(int id)
        {
            var album = context.Albums.Find(id);
            return View(album);
        }
        // GET: /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = context.Genres.ToList();
            return PartialView(genres);
        }
    }
}

MvcMusicStore333/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")"
          rel="stylesheet"
          type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")"
            type="text/javascript"></script>
</head>
<body>
    <div id="header">
        <h1>
            <a href="/">
                ASP.NET MVC MUSIC
                STORE
            </a>
        </h1>
        <ul id="navlist">
            <li class="first">
                <a href="@Url.Content("~")" id="current">
                    Home
                </a>
            </li>
            <li><a href="@Url.Content("~/Store/")">Store</a></li>
            <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
            <li>
                <a href="@Url.Content("~/StoreManager/")">
                    Admin
                </a>
            </li>
        </ul>
    </div>
    @{Html.RenderAction("GenreMenu", "Store");}
    <div id="main">
        @RenderBody()
    </div>
    <div id="footer">
        built with <a href="http://asp.net/mvc">ASP.NET MVC 3</a>
    </div>
</body>
</html>